### ISSUE TITLE
before/after insert questions

### ISSUE THREAD

**Issue by denkomanceski** [alekbarszczewski/knex-hooks#1]
Do ```getUpdateData``` and ```getInsertData``` make call to the database? regards

**Comment by alekbarszczewski** [comment]
Nope, `getUpdateData` and `getInsertData` are just helpers to extract insert/update data from query builder:

```js
const query = knex('users').insert({ name: 'john' }); // <-- this is query builder instance
const data = getInsertData(query);
console.log(data); // will print { name: 'john' }
```

```js
const query = knex('users').update({ name: 'john' }); // <-- this is query builder instance
const data = getUpdateData(query);
console.log(data); // will print { name: 'john' }
```

Look at the code here https://github.com/alekbarszczewski/knex-hooks/blob/master/src/helpers.js#L8 - these helper methods are very simple. I implemented them because in hooks you usually want to interact with data passed to insert/update (to modify inserted/updated data), but Knex does not provide any methods to extract those.

---

Query builder instance is passed to hook(s) in argument `params.query`.

Cheers

**Comment by denkomanceski** [comment]
Perfect thanks! Its an awesome library!

**Comment by alekbarszczewski** [comment]
Thanks, I am glad it's useful :)
